title: "Diego Andrés Barbosa Trujillo"
description: "Portfolio and AI/ML blog"
url: "https://dabarbosa10.github.io"
baseurl: ""              # keep empty for user site
theme: minima

markdown: kramdown
kramdown:
  input: GFM
