# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

# -- Site Settings --
title: Diego Andres Barbosa Trujillo ML/AI Blog        # The title of your site.
description: "This is a blog about ML/AI topics. It is my way to learn, better understand, and discuss machine learning and artificial intelligence."
future: true

# -- Theme Settings --
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-remote-theme  # <-- ADD THIS LINE
  - jekyll-include-cache

# -- Navigation Links --
main:
  - title: "Home"
    url: /
  - title: "ML/AI Writings"
    url: /blog/